services:
  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: cloudsigma.com/php
    container_name: govee-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html/
    networks:
      - app-network
    ports:
        - "82:80"
    volumes:
      - ./test.txt:/var/www/html/
      - ./:/var/www/html
  #MySQL Service
  db:
    image: mysql:5.7.32
    container_name: govee-db
    restart: unless-stopped
    tty: true
    platform: linux/x86_64
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: "goveeDB"
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_HOST: ${DB_HOST}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - app-network
    volumes:
        - ./db:/var/lib/mysql

#Docker Networks
networks:
  app-network:
    driver: bridge
